swagger: "2.0"
info:
  openapi: "3.1.0"
  title: "League Master - APIs"
  description: "This documentation describes all the APIs related to League Master."
  version: 1.0.0
  servers:
    -url: http://192.168.18.45:4000
    description: "local server"
schemes: [http]
securityDefinitions:
  BearerToken:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    scheme: "bearer"
    bearerFormat: "JWT"
security:
  -BearerToken: []

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: "Registers a new user"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          description: Username of the user
          required: true
          type: string
        - name: password
          in: formData
          description: Password of the user
          required: true
          type: string
      responses:
        200:
          description: "User registered successfully"
        404:
          description: "Invalid Payload"
        500:
          description: "Internal Server Error"

  /auth/activate/{token}:
    put:
      tags:
        - Auth
      summary: "Activates a user account"
      description: "This API activates a user account using verification token."
      parameters:
        - name: token
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Account activation successful"
        403:
          description: "Description1: User isn't authorised to access this page, Description2: Token is expired. Please register again."
        409:
          description: "Account is already activated"
        500:
          description: "Internal Server Error"

  /auth/login:
    post:
      tags:
        - Auth
      summary: "User login"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          description: Username of the user
          required: true
          type: string
        - name: password
          in: formData
          description: Password of the user
          required: true
          type: string
      responses:
        200:
          description: "User login successful"
        404:
          description: "Invalid Payload"
        403:
          description: "Description1: Invalid Credentials, Description2: Account isn't activated"
        500:
          description: "Internal Server Error"
  /auth/verify:
    post:
      tags:
        - Auth
      summary: "Username verification"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          description: Username of the user
          required: true
          type: string
      responses:
        200:
          description: "Username is valid"
        404:
          description: "Invalid Payload"
        403:
          description: "Description1: Invalid username, Description2: Account isn't activated"
        500:
          description: "Internal Server Error"
  /auth/reset/{token}:
    put:
      tags:
        - Auth
      summary: "Password reset"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: token
          in: path
          description: Reset token of the user
          required: true
          type: string
        - name: password
          in: formData
          description: Password of the user
          required: true
          type: string
      responses:
        200:
          description: "Password reset successful"
        404:
          description: "Invalid Payload"
        403:
          description: "Description1: User isn't authorised to access this page, Description2: Token is expired. Please register again."
        500:
          description: "Internal Server Error"
