swagger: "2.0"
info:
  openapi: "3.1.0"
  title: "League Master - APIs"
  description: "This documentation describes all the APIs related to League Master."
  version: 1.0.0
  servers:
    -url: http://192.168.18.45:4000
    description: "local server"
schemes: [http]
securityDefinitions:
  BearerToken:
    type: "apiKey"
    name: "token"
    in: "cookies"
    scheme: "bearer"
    bearerFormat: "JWT"
security:
  - BearerToken: []

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: "Registers a new user"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          description: Username of the user
          required: true
          type: string
        - name: password
          in: formData
          description: Password of the user
          required: true
          type: string
      responses:
        200:
          description: "User registered successfully"
        404:
          description: "Invalid Payload"
        500:
          description: "Internal Server Error"

  /auth/activate/{token}:
    put:
      tags:
        - Auth
      summary: "Activates a user account"
      description: "This API activates a user account using verification token."
      parameters:
        - name: token
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Account activation successful"
        403:
          description: "Description1: User isn't authorised to access this page, Description2: Token is expired. Please register again."
        409:
          description: "Account is already activated"
        500:
          description: "Internal Server Error"

  /auth/login:
    post:
      tags:
        - Auth
      summary: "User login"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          description: Username of the user
          required: true
          type: string
        - name: password
          in: formData
          description: Password of the user
          required: true
          type: string
      responses:
        200:
          description: "User login successful"
        404:
          description: "Invalid Payload"
        403:
          description: "Description1: Invalid Credentials, Description2: Account isn't activated"
        500:
          description: "Internal Server Error"
  /auth/verify:
    post:
      tags:
        - Auth
      summary: "Username verification"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          description: Username of the user
          required: true
          type: string
      responses:
        200:
          description: "Username is valid"
        404:
          description: "Invalid Payload"
        403:
          description: "Description1: Invalid username, Description2: Account isn't activated"
        500:
          description: "Internal Server Error"
  /auth/reset/{token}:
    put:
      tags:
        - Auth
      summary: "Password reset"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: token
          in: path
          description: Reset token of the user
          required: true
          type: string
        - name: password
          in: formData
          description: Password of the user
          required: true
          type: string
      responses:
        200:
          description: "Password reset successful"
        404:
          description: "Invalid Payload"
        403:
          description: "Description1: User isn't authorised to access this page, Description2: Token is expired. Please register again."
        500:
          description: "Internal Server Error"
  /league/create:
    post:
      tags:
        - League
      summary: "Create a League"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: leagueName
          in: formData
          description: Name of the league user want to create.
          required: true
          type: string
        - name: type
          in: formData
          description: Type of the league
          required: true
          type: string
      responses:
        200:
          description: "League created successfully"
        500:
          description: "Internal Server Error"
  /league/types:
    get:
      tags:
        - League
      summary: "Fetch all League types"
      produces:
        - application/json
      responses:
        200:
          description: "Fetched all league types successfully"
        500:
          description: "Internal Server Error"
  /league/leagues:
    get:
      tags:
        - League
      summary: "Fetch all User Leagues"
      produces:
        - application/json
      responses:
        200:
          description: "Fetched all user leagues successfully"
        500:
          description: "Internal Server Error"

  /league/join:
    put:
      tags:
        - League
      summary: "Join new league"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: leagueCode
          in: formData
          description: Code of the league user want to join.
          required: true
          type: string
      responses:
        200:
          description: "Fetched all user leagues successfully"
        400:
          description: "Invalid Payload"
        404:
          description: "League code is invalid"
        409:
          description: "You're already part of this team"
        500:
          description: "Internal Server Error"

  /league/{leagueId}:
    get:
      tags:
        - League
      summary: "Get League"
      produces:
        - application/json
      parameters:
        - name: leagueId
          in: path
          description: Id of the league.
          required: true
          type: number
      responses:
        200:
          description: "Fetched all league data successfully"
        404:
          description: "League not found"
        500:
          description: "Internal Server Error"

  /user/profile:
    get:
      tags:
        - User
      summary: "Fetch user profile"
      produces:
        - application/json
      responses:
        200:
          description: "Fetched user profile successfully"
        403:
          description: "User isn't authorised"
        500:
          description: "Internal Server Error"

  /user/username:
    put:
      tags:
        - User
      summary: "Update user's username"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          description: New username of the user.
          required: true
          type: string
      responses:
        200:
          description: "Username updated successfully"
        403:
          description: "User isn't authorised"
        409:
          description: "Username already exists"
        500:
          description: "Internal Server Error"

  /user/password:
    put:
      tags:
        - User
      summary: "Update user's password"
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: currentPassword
          in: formData
          description: Current password of the user.
          required: true
          type: string
        - name: newPassword
          in: formData
          description: New password of the user.
          required: true
          type: string
      responses:
        200:
          description: "Username updated successfully"
        403:
          description: "User isn't authorised"
        409:
          description: "Username already exists"
        500:
          description: "Internal Server Error"

  /user:
    put:
      tags:
        - User
      summary: "Deletes user account"
      responses:
        200:
          description: "User deleted successfully"
        401:
          description: "Description 1: User isn't authorised, Description 2: Invalid Password,"
        500:
          description: "Internal Server Error"
